import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

//components
import { Header } from "@/components/Header";
import Particles from "./components/particles";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
         className={`${poppins.variable} antialiased min-h-screen bg-gradient-to-tl from-[#030014] via-purple-800/10 to-[#030014]`}
      >
             <Particles
                className="absolute inset-0 -z-10 animate-fade-in"
                quantity={100}
              />
        <Header />
        {children}
      </body>
    </html>
  );
}
