import type { Metadata } from "next";
import { Poppins, JetBrains_Mono } from "next/font/google";
import "./globals.css";

//components
import { Header } from "@/components/navigation/Header";
import Particles from "../components/ui/particles";
import { PageTransition } from "@/components/transitions/PageTransition";
import { StairTransition } from "@/components/transitions/StairTransition";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${poppins.variable} ${jetbrainsMono.variable} antialiased min-h-screen bg-primary`}
        // className={`${poppins.variable} ${jetbrainsMono.variable} antialiased min-h-screen bg-gradient-to-tl from-black via-zinc-800/20 to-black`}
        // className={`${poppins.variable} ${jetbrainsMono.variable} antialiased min-h-screen bg-gradient-to-tl from-[#030014] via-purple-800/10 to-[#030014]`}
      >
        <Particles
          className="absolute inset-0 -z-10 animate-fade-in"
          quantity={100}
        />
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
